version: '2'

services:
  parse-server:
    build: .
    command: npm run dev:parse-server
    env_file: .env
    ports:
      - 1337:1337
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  live-query-server:
    build: .
    command: npm run dev:live-query-server
    env_file: .env
    ports:
      - 1338:1338
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  parse-dashboard:
    build: .
    command: ./node_modules/.bin/parse-dashboard
    env_file: .env
    ports:
      - 4040:4040
  mongodb:
    image: mongo:3.6.3
    volumes:
      - mongodb:/data/db
      - mongodb:/data/configdb
    ports:
      - 27017:27017
  redis:
    image: redis:4.0.8
    command: redis-server --save "" --appendonly no

volumes:
  mongodb:
    driver: local
